# Generated by Django 6.0.4 on 2026-04-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketwatch', '0002_admin_monitor_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorsettings',
            name='alert_email_recipients',
            field=models.TextField(blank=True, help_text='One email per line, or comma-separated.', verbose_name='Alert email recipients'),
        ),
        migrations.AddField(
            model_name='monitorsettings',
            name='email_alerts_enabled',
            field=models.BooleanField(default=False, verbose_name='Email alerts enabled'),
        ),
        migrations.AddField(
            model_name='monitorsettings',
            name='telegram_alerts_enabled',
            field=models.BooleanField(default=False, verbose_name='Telegram alerts enabled'),
        ),
        migrations.AddField(
            model_name='monitorsettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=128, verbose_name='Telegram bot token'),
        ),
        migrations.AddField(
            model_name='monitorsettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram chat id'),
        ),
    ]
