# Generated by Django 6.0.4 on 2026-04-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketwatch', '0003_monitorsettings_alert_email_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorsettings',
            name='telegram_last_summary_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Telegram last summary at'),
        ),
        migrations.AddField(
            model_name='monitorsettings',
            name='telegram_summary_interval_minutes',
            field=models.PositiveIntegerField(default=5, verbose_name='Telegram summary interval minutes'),
        ),
    ]
