# Generated by Django 6.0.4 on 2026-04-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketwatch', '0004_monitorsettings_telegram_last_summary_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorsettings',
            name='alert_email_recipients',
        ),
        migrations.RemoveField(
            model_name='monitorsettings',
            name='email_alerts_enabled',
        ),
    ]
