# Generated by Django 6.0.4 on 2026-05-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketwatch', '0005_remove_monitorsettings_alert_email_recipients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketquote',
            name='symbol',
            field=models.CharField(max_length=96, unique=True),
        ),
        migrations.AlterField(
            model_name='monitorcard',
            name='compare_exchange',
            field=models.CharField(choices=[('Binance', 'Binance'), ('Nobitex', 'Nobitex'), ('Wallex', 'Wallex'), ('Bitbank', 'Bitbank')], default='Binance', max_length=32, verbose_name='مقایسه با'),
        ),
        migrations.AlterField(
            model_name='monitorcard',
            name='reference_exchange',
            field=models.CharField(choices=[('Wallex', 'Wallex'), ('Bitbank', 'Bitbank')], default='Wallex', max_length=32, verbose_name='قیمت مرجع'),
        ),
        migrations.AlterField(
            model_name='monitorcard',
            name='symbol',
            field=models.CharField(help_text='مثلا BTCUSDT', max_length=24, verbose_name='نام کارت'),
        ),
        migrations.AddConstraint(
            model_name='monitorcard',
            constraint=models.UniqueConstraint(fields=('symbol', 'reference_exchange', 'compare_exchange'), name='unique_monitor_card_route'),
        ),
    ]
