# Generated by Django 6.0.4 on 2026-05-05 07:28

from django.db import migrations, models


def copy_minutes_to_seconds(apps, schema_editor):
    MonitorSettings = apps.get_model('marketwatch', 'MonitorSettings')
    for settings in MonitorSettings.objects.all():
        settings.sync_interval_seconds = max(1, settings.sync_interval_minutes * 60)
        settings.save(update_fields=['sync_interval_seconds'])


class Migration(migrations.Migration):

    dependencies = [
        ('marketwatch', '0006_alter_marketquote_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorsettings',
            name='sync_interval_seconds',
            field=models.PositiveIntegerField(default=60, verbose_name='ثانیه\u200cهای سینک / داده\u200cگیری'),
        ),
        migrations.RunPython(copy_minutes_to_seconds, migrations.RunPython.noop),
    ]
