# Generated by Django 6.0.4 on 2026-05-05 09:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketwatch', '0007_monitorsettings_sync_interval_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketquote',
            name='bitbank_spread_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketquote',
            name='bitbank_spread_percent',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='marketquote',
            name='bitbank_spread_status',
            field=models.CharField(default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='monitorcard',
            name='spread_alert_color',
            field=models.CharField(choices=[('green', 'سبز'), ('blue', 'آبی'), ('gray', 'خاکستری'), ('yellow', 'زرد'), ('red', 'قرمز'), ('purple', 'Purple'), ('magenta', 'Magenta')], default='purple', max_length=16, verbose_name='Bitbank spread alert color'),
        ),
        migrations.AddField(
            model_name='monitorcard',
            name='spread_siren_enabled',
            field=models.BooleanField(default=True, verbose_name='Bitbank spread siren'),
        ),
        migrations.AddField(
            model_name='monitorcard',
            name='spread_threshold_percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.2'), help_text='Only applies when the source exchange is Bitbank.', max_digits=18, verbose_name='Bitbank spread threshold (%)'),
        ),
        migrations.AddField(
            model_name='monitorsettings',
            name='bitbank_spread_interval_seconds',
            field=models.PositiveIntegerField(default=5, verbose_name='Bitbank spread sync seconds'),
        ),
        migrations.AddField(
            model_name='monitorsettings',
            name='last_spread_synced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Bitbank last spread sync'),
        ),
        migrations.AlterField(
            model_name='monitorcard',
            name='normal_color',
            field=models.CharField(choices=[('green', 'سبز'), ('blue', 'آبی'), ('gray', 'خاکستری'), ('yellow', 'زرد'), ('red', 'قرمز'), ('purple', 'Purple'), ('magenta', 'Magenta')], default='green', max_length=16, verbose_name='رنگ کارت در حالت عادی'),
        ),
    ]
