# Generated by Django 6.0.4 on 2026-05-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketwatch', '0008_marketquote_bitbank_spread_fetched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketquote',
            name='bitbank_spread_abs',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True),
        ),
    ]
