# Generated by Django 6.0.4 on 2026-05-05 10:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketwatch', '0009_marketquote_bitbank_spread_abs'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcard',
            name='spread_fast_threshold_percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.5'), help_text='When spread passes this level, the Bitbank spread siren runs faster.', max_digits=18, verbose_name='Bitbank fast spread threshold (%)'),
        ),
    ]
