# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketwatch", "0010_monitorcard_spread_fast_threshold_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorsettings",
            name="telegram_update_offset",
            field=models.BigIntegerField(blank=True, editable=False, null=True, verbose_name="Telegram update offset"),
        ),
        migrations.CreateModel(
            name="TelegramSubscriber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chat_id", models.CharField(max_length=64, unique=True)),
                ("chat_type", models.CharField(blank=True, max_length=32)),
                ("title", models.CharField(blank=True, max_length=128)),
                ("username", models.CharField(blank=True, max_length=128)),
                ("first_name", models.CharField(blank=True, max_length=128)),
                ("last_name", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["chat_id"],
            },
        ),
    ]
